### PR TITLE
Add an article on tried & rejected alternatives to TT

### PR DESCRIPTION
**Pull request by mikesamuel**
This should be viewable via wicg.github.io/trusted-types/design-history.html.

### CODE REVIEW

**Comment by Siegrift** [comment]
@mikesamuel I get 404 on [wicg.github.io/trusted-types/design-history.html](wicg.github.io/trusted-types/design-history.html).

**Comment by mikesamuel** [comment]
>  I get 404 on wicg.github.io/trusted-types/design-history.html

@Siegrift That's where it would live once integrated

https://raw.githack.com/mikesamuel/trusted-types/design-history/design-history.html should work in the meantime.

**Comment by koto** [comment]
Could you add the content into the wiki instead?

**Comment by mikesamuel** [comment]
@koto Ported to https://github.com/WICG/trusted-types/wiki/design-history .  The images fetch from my fork which is probably a tad brittle.

**Comment by mikesamuel** [comment]
Obviated by wiki.  Closing.

**Pull request closed without merging**
