### PR TITLE
Use CG-DRAFT status

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by mikesamuel** [comment]
Thanks.   Should this cause a visible change?  If so, maybe `npm run spec` and git add dist/spec/index.html

**Comment by marcoscaceres** [comment]
It will after the following lands: https://github.com/tabatkins/bikeshed/issues/1460

**Comment by mikesamuel** [comment]
The status change looks good to me per https://tabatkins.github.io/bikeshed/#metadata-status

It looks like it should affect the HTML output:

https://github.com/WICG/trusted-types/blob/f661e6d3ddc75b394b9c66d2c8c9eb3a6bc99b69/dist/spec/index.html#L1463-L1464

so please run `npm run build` and add the regenerated dist/spec/index.html to this PR.

**Comment by marcoscaceres** [comment]
Tried `npm run build` but didn't generate any changes in dist/... not sure if BikeShed needs updating since that fix or something?

**Comment by mikesamuel** [comment]
Sorry, I said`npm run spec` the [first time](https://github.com/WICG/trusted-types/pull/146#issuecomment-485147895) but borked it the second time.

**Comment by marcoscaceres** [comment]
done, thanks for the help!

**Comment by koto** [comment]
Merged. Thanks, Marcos!

**Pull request merged**
